### ISSUE TITLE
Setup CLI with color 

### ISSUE THREAD

**Issue by mattfarina** [mattfarina/hypper#1]
Zypper has color output. This isn't unusual in modern CLI interfaces. The CLI will often try to detect if colors can be used and only use them when it will work. Along with this there is often an opt-out. Colors, such as red, can make it easier to spot errors.

This issue is to add that capability to `cmd/hypper`. A 3rd party library should be used for this.

**Comment by dragonchaser** [comment]
blocked by #6 and #5 (we want that in place before we open the pr)

**Comment by mattfarina** [comment]
I had some thoughts on colors that I put on the log library... https://github.com/mattfarina/log/issues/4
